// popup.js — settings management and PDF parsing

// ─── Elements ────────────────────────────────────────────────────────────────

const apiKeyInput   = document.getElementById('api-key');
const resumeText    = document.getElementById('resume-text');
const pdfInput      = document.getElementById('pdf-input');
const uploadArea    = document.getElementById('upload-area');
const uploadText    = document.getElementById('upload-text');
const targetRole    = document.getElementById('target-role');
const seniority     = document.getElementById('seniority');
const locationInput = document.getElementById('location');
const notes         = document.getElementById('notes');
const saveBtn       = document.getElementById('save-btn');
const statusBar     = document.getElementById('status-bar');
const statusText    = document.getElementById('status-text');

// ─── Load saved settings ──────────────────────────────────────────────────────

chrome.storage.local.get(['resumeText', 'apiKey', 'preferences'], (data) => {
  if (data.apiKey)     apiKeyInput.value = data.apiKey;
  if (data.resumeText) resumeText.value  = data.resumeText;

  if (data.preferences) {
    const p = data.preferences;
    if (p.targetRole) targetRole.value   = p.targetRole;
    if (p.seniority)  seniority.value    = p.seniority;
    if (p.location)   locationInput.value = p.location;
    if (p.notes)      notes.value        = p.notes;
  }

  updateStatus();
});

// ─── PDF Upload ───────────────────────────────────────────────────────────────

pdfInput.addEventListener('change', async (e) => {
  const file = e.target.files[0];
  if (!file) return;

  uploadText.innerHTML = '⏳ Extracting text from PDF…';
  uploadArea.classList.remove('has-file');

  try {
    const text = await extractTextFromPDF(file);
    if (text.length < 50) throw new Error('Could not extract enough text. Try pasting manually.');
    resumeText.value = text;
    uploadArea.classList.add('has-file');
    uploadText.innerHTML = `<span class="success">✓ ${file.name} — ${text.length} characters extracted</span>`;
  } catch (err) {
    uploadText.innerHTML = `<strong style="color:#e74c3c">⚠ ${err.message}</strong><br><span style="color:#666">Please paste your resume text below instead.</span>`;
  }
});

// Simple PDF text extractor (works for most CV PDFs generated by Word/Google Docs)
async function extractTextFromPDF(file) {
  const buffer = await file.arrayBuffer();
  const bytes = new Uint8Array(buffer);
  const raw = new TextDecoder('latin1').decode(bytes);

  const parts = [];

  // Extract text from BT...ET blocks
  const btEtRegex = /BT([\s\S]*?)ET/g;
  let blockMatch;
  while ((blockMatch = btEtRegex.exec(raw)) !== null) {
    const block = blockMatch[1];

    // (text) Tj
    const tjRegex = /\(([^)\\]*(?:\\.[^)\\]*)*)\)\s*Tj/g;
    let m;
    while ((m = tjRegex.exec(block)) !== null) {
      parts.push(decodePdfString(m[1]));
    }

    // [(text) -num (text)] TJ
    const tjArrRegex = /\[([\s\S]*?)\]\s*TJ/g;
    while ((m = tjArrRegex.exec(block)) !== null) {
      const inner = m[1];
      const strRegex = /\(([^)\\]*(?:\\.[^)\\]*)*)\)/g;
      let sm;
      while ((sm = strRegex.exec(inner)) !== null) {
        parts.push(decodePdfString(sm[1]));
      }
    }
  }

  // Also try to grab plain text streams for newer PDFs
  const streamRegex = /stream\r?\n([\s\S]*?)\r?\nendstream/g;
  let sm;
  while ((sm = streamRegex.exec(raw)) !== null) {
    const s = sm[1];
    if (s.startsWith('%PDF') || s.includes('xref')) continue; // skip binary
    // Only include if mostly printable ASCII
    const printable = s.replace(/[^\x20-\x7E\n]/g, '');
    if (printable.length > 50 && printable.length / s.length > 0.6) {
      parts.push(printable);
    }
  }

  return parts
    .join(' ')
    .replace(/\\n/g, '\n')
    .replace(/\\r/g, ' ')
    .replace(/\\t/g, ' ')
    .replace(/\s{3,}/g, '\n')
    .trim();
}

function decodePdfString(s) {
  return s
    .replace(/\\n/g, '\n')
    .replace(/\\r/g, ' ')
    .replace(/\\t/g, ' ')
    .replace(/\\\\/g, '\\')
    .replace(/\\\(/g, '(')
    .replace(/\\\)/g, ')');
}

// ─── Save ─────────────────────────────────────────────────────────────────────

saveBtn.addEventListener('click', () => {
  const key    = apiKeyInput.value.trim();
  const resume = resumeText.value.trim();

  if (!key) {
    flash(saveBtn, 'Add your API key first', '#e74c3c');
    return;
  }

  if (!resume) {
    flash(saveBtn, 'Add your resume first', '#e74c3c');
    return;
  }

  const preferences = {
    targetRole: targetRole.value.trim(),
    seniority:  seniority.value,
    location:   locationInput.value.trim(),
    notes:      notes.value.trim()
  };

  chrome.storage.local.set({
    apiKey:      key,
    resumeText:  resume,
    preferences
  }, () => {
    flash(saveBtn, '✓ Saved — refresh LinkedIn to activate', '#27ae60');
    updateStatus(true);
  });
});

// ─── Status bar ───────────────────────────────────────────────────────────────

function updateStatus(justSaved = false) {
  const key    = apiKeyInput.value.trim();
  const resume = resumeText.value.trim();

  if (justSaved && key && resume) {
    statusBar.className = 'status-bar ready';
    statusText.textContent = '✓ Ready — JobLens is active on LinkedIn jobs pages';
    return;
  }

  if (key && resume) {
    statusBar.className = 'status-bar ready';
    statusText.textContent = '✓ Ready — JobLens is active on LinkedIn jobs pages';
  } else {
    statusBar.className = 'status-bar missing';
    const missing = [];
    if (!key)    missing.push('API key');
    if (!resume) missing.push('resume');
    statusText.textContent = `Missing: ${missing.join(' and ')}`;
  }
}

function flash(btn, message, color) {
  const original = btn.textContent;
  const originalBg = btn.style.background;
  btn.textContent = message;
  btn.style.background = color;
  setTimeout(() => {
    btn.textContent = original;
    btn.style.background = originalBg;
  }, 2500);
}

// Live status update as user types
apiKeyInput.addEventListener('input', updateStatus);
resumeText.addEventListener('input', updateStatus);
